### ISSUE TITLE
[BUG] java.lang.NoClassDefFoundError: javafx/embed/swing/JFXPanel when authenticating with Webview

### ISSUE THREAD

**Issue by pauljako** [TheShark34/OpenAuth#48]
**Describe the bug**
When I call authenticator.loginWithWebview() I get the following error:
```
java.lang.NoClassDefFoundError: javafx/embed/swing/JFXPanel
	at fr.litarvan.openauth.microsoft.MicrosoftAuthenticator.loginWithAsyncWebview(MicrosoftAuthenticator.java:154)
	at fr.litarvan.openauth.microsoft.MicrosoftAuthenticator.loginWithWebview(MicrosoftAuthenticator.java:138)
	at de.pauljako.airclient.Account.webLogin(Account.java:60)
```

**To Reproduce**
1. Make a Simple Code that calls loginWithWebview()
2. Execute it
3. See error

**Expected behavior**
WebView should Open

**Desktop**
 - OS: macOS 14
 - Java version 17.0.10-temurin (aarch64)
 - Version [What Version ?]

**Comment by blockitjimjam** [comment]
I have this exact issue. it is so frustrating
